# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resources/proto/main.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'resources/proto/main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aresources/proto/main.proto\x12\x04grpc\"(\n\x07Request\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06shipid\x18\x02 \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04mess\x18\x01 \x01(\t2;\n\x0c\x43onfirmEmail\x12+\n\ncheckEmail\x12\r.grpc.Request\x1a\x0e.grpc.ResponseB\x16\n\x12src.grpcServer.genP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resources.proto.main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022src.grpcServer.genP\001'
  _globals['_REQUEST']._serialized_start=36
  _globals['_REQUEST']._serialized_end=76
  _globals['_RESPONSE']._serialized_start=78
  _globals['_RESPONSE']._serialized_end=102
  _globals['_CONFIRMEMAIL']._serialized_start=104
  _globals['_CONFIRMEMAIL']._serialized_end=163
# @@protoc_insertion_point(module_scope)
